services:
  - type: web
    name: ecommerce-node-app
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        value: N.Honest Supermarket
